### ISSUE TITLE
Load LegendaryClothes-ArmorSmith-Merged.esp after Armorsmith Extended.esp

### ISSUE THREAD

**Issue by Freso** [loot/fallout4#1]
[Acleacius writes](http://forums.bethsoft.com/topic/1557786-rel-loot-thread-21/?p=24706484):

> Not sure where to report this but the LOOT forum link for Fallout 4 leads here. I was trying to report 'LegendaryClothes-ArmorSmith-Merged.esp ' should be listed after 'Armorsmith Extended.esp' . Otherwise Legendary Clothing will not work as currently listed before 'Armorsmith Extended.esp' in the load order.

**Comment by Freso** [comment]
- [x] What are the Nexus (or other) URLs for the involved mods?
- [ ] Is LOOT currently actually sorting them in the wrong order?

**Comment by shadowslasher410** [comment]
Don't know if they're being sorted wrong (don't use either of them), but judging from a quick search (I may be wrong) I believe the urls are:
http://www.nexusmods.com/fallout4/mods/2228 -Armorsmith Extended
http://www.nexusmods.com/fallout4/mods/3694 -Legendary Clothes
Also, from Legendary Clothes main page: 
"If you are using Armorsmith Extended v2.0 and up, you do not need this mod, as this mod's functionality was integrated into Armorsmith Extended. This mod is for people that aren't using Armorsmith Extended and want to use Legendary Modification."
