### ISSUE TITLE
comparability patch false information

### ISSUE THREAD

**Issue by TynotWolfDragon** [loot/fallout4#119]
the plugin "CustomizableNeeds + RealisticAidSideEffects.esp" has a warning that reads : "You seem to be using Lore-Friendly Survival Chems, but you have not enabled a compatibility patch for this mod. A compatibility patch is included with this plugin's installer." 
While I am infact using LFSC, I do infact have the compatibility patch enabled.

**Comment by MacSplody** [comment]
@TynotWolfDragon Thanks for reporting that issue. 
I've made a change https://github.com/loot/fallout4/commit/c417b088b2eadec5b380a188d2729f5f0986c6c3 to correct the message still being displayed when the patch is active.
Can you update your masterlist and test?

**Comment by TynotWolfDragon** [comment]
i would love to, but my sisters cat just chewed through my ethernet cable a while ago. hoing to have to wait till i can get a new one.
