### ISSUE TITLE
Only FO4 Master Showing Active; Issues Sorting (Alphabetical Order)

### ISSUE THREAD

**Issue by Aeradom** [loot/fallout4#13]
I actually have two issues, though only one I'm able to replicated. I had this issue the other night but was able to manage to get it work by making the load order and the plugins .txt files to read only and not, but I'm sure how to replicate the issue as I've tried multiple times. I've also made sure I have the most recent one, and have reinstalled it, twice actually. 

The second issue though before this one is that when I'd have the mods sort, the non-ESM files would seem to be sorted in alphabetical order. I think there were a few that wasn't that way though, and as I recall, I think the ones that were set, were actually in the DLClist.txt, though I'm not entirely sure. In any case, this is what I got and I hope you can help as I'm wanting to hold off on playing until everything is set. 

[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/227196/LOOTDebugLog.txt)
[CEFDebugLog.txt](https://github.com/loot/fallout4/files/227197/CEFDebugLog.txt)

Oh damn it, I put it in the FO4 section, and I think this might be an issue with the actual LOOT program. Then again, I probably don't know so I'll leave that up to you guys to decide, as you all will be more informed.

**Comment by Aeradom** [comment]
So as a last ditched effort I restarted the computer and then deleted the folder itself. Then created a new folder and extracted the contents right into the folder. I opened it on it's own and sure enough it's working. If it comes up again I'll report back, but as of this moment, I guess it's resolved.

**Comment by Ortham** [comment]
> The second issue though before this one is that when I'd have the mods sort, the non-ESM files would seem to be sorted in alphabetical order.

If LOOT doesn't think plugins should go in a particular order, and they don't have existing load order positions, it will order them alphabetically, so this doesn't sound like an issue, unless you know a particular plugin's position is wrong (and then you'll need to give specifics so metadata can be added for it).

**Comment by Aeradom** [comment]
I understand that I suppose, it's just that, sometimes it won't sort that way which was why I thought it was odd. Like now it's seems pretty mixed up in terms of esps, so I can't exactly replicate it sadly.
