### ISSUE TITLE
26 Creation Club plugins not being added to group

### ISSUE THREAD

**Issue by FenghuangZero** [loot/fallout4#139]
A large number of Creation Club Plugins are not being added to the ccGroup correctly due to not following existing naming convention. The existing Regex can be seen on line 912.
`  - name: 'cc[A-Z]{3}FO4[0-9]{3}-[a-zA-Z0-9()]+\.es(l|m)'
    group: *ccGroup`

This does not catch the following cases 
- 'cczsef04001-bhouse.esm' which mistakenly entered a zero instead of the letter 'o' in 'fo4'.
- 'ccqdrfo4001_powerarmorai.es;', 'ccsbjfo4002_manwellrifle.esl' & 'cctosfo4002_neonflats.es,' which have an underscore instead of a hyphen between the plugin name and number designator.
- 'ccbgsfo4091-as_bats.esl', 'ccbgsfo4092-as_camoblue.esl', 'ccbgsfo4093-as_camogreen.esl', 'ccbgsfo4094-as_camotan.esl', 'ccbgsfo4095-as_childrenofatom.esl', 'ccbgsfo4096-as_enclave.esl', 'ccbgsfo4097-as_jack-olantern.esl', 'ccbgsfo4098-as_pickman.esl', 'ccbgsfo4099-as_reillysrangers.esl', 'ccbgsfo4101-as_shi.esl', 'ccbgsfo4103-as_tunnelsnakes.esl', 'ccbgsfo4104-ws_bats.esl', 'ccbgsfo4105-ws_camoblue.esl', 'ccbgsfo4106-ws_camogreen.esl', 'ccbgsfo4107-ws_camotan.esl',  'ccbgsfo4108-ws_childrenofatom.esl', 'ccbgsfo4110-ws_enclave.esl', 'ccbgsfo4111-ws_jack-olantern.esl', 'ccbgsfo4112-ws_pickman.esl', 'ccbgsfo4113-ws_reillysrangers.esl', 'ccbgsfo4114-ws_shi.esl', & 'ccbgsfo4104-ws_tunnelsnakes.esl' which have an underscore or hyphen as part of the plugin name.

The majority of these can be resolved by matching the equivalent expression from the SSE masterlist, which would appear as follows
`  - name: 'cc[A-Z]{3}FO4[0-9]{3}.*\.es(l|m)'`
This would only leave the Charlstown Condo plugin 'cczsef04001-bhouse.esm' as not being caught. This can be resolved by either manually designating the group for this plugin, or by adding a check for either/or o and 0, which I believe would appear as follows.
`  - name: 'cc[A-Z]{3}F(O|0)4[0-9]{3}.*\.es(l|m)'`

**Comment by MacSplody** [comment]
> This would only leave the Charlstown Condo plugin 'cczsef04001-bhouse.esm' as not being caught. This can be resolved by either manually designating the group for this plugin, or by adding a check for either/or o and 0, which I believe would appear as follows.
> ` - name: 'cc[A-Z]{3}F(O|0)4[0-9]{3}.*\.es(l|m)'`

That looks fine to me, the condition for the global message "This version of LOOT has inferior handling of Creation Club plugins." should be updated as well.

```yaml
    condition: 'version("LOOT", "0.13.1.0", <) and file("cc[A-Z]{3}SSE[0-9]{3}.*\.es(l|m)")'
```

**Comment by MacSplody** [comment]
@FenghuangZero Done in https://github.com/loot/fallout4/commit/cccb8376f58919ae2366b83037153b26f6b2977f.
