### ISSUE TITLE
Diamond City Expansion and Depravity

### ISSUE THREAD

**Issue by Jeoshua** [loot/fallout4#169]
LOOT consistently gets the order of these two mods wrong. [Diamond City Expansion](https://www.nexusmods.com/fallout4/mods/21853) `Stm_DiamondCityExpansion.esp` must come after [Depravity - A Harmless Bit of Fun](https://www.nexusmods.com/fallout4/mods/35513) `Depravity.esp`, or the precombines break and Diamond City becomes unplayable. This is easily fixed in the standalone version by manually adding tags, but this is not the case for Mod Organizer 2.

Edited by @CptMcSplody : Added links to mods, & plugin names.

- [x] Sort Diamond City Expansion after Depravity.

**Comment by MacSplody** [comment]
> LOOT consistently gets the order of these two mods wrong.

LOOT is meant to be consistent and optimal, larger plugins will generally be sorted earlier.
`Stm_DiamondCityExpansion.esp` has 25k+ records.
`Depravity.esp` has 18k+ records.
It has no way to verify if it's correct, that's where user feedback comes in.

> Diamond City Expansion must come after Depravity, or the precombines break and Diamond City becomes unplayable.

Yeah it's reverting a few changes, an after can be added for that.

![image](https://user-images.githubusercontent.com/1944639/83923139-89066300-a779-11ea-8aad-7eb1711493ab.png)

> This is easily fixed in the standalone version by manually adding tags, but this is not the case for Mod Organizer 2.

MO2 only provides a sort button, they'd need to use the actual LOOT program as well for adding user metadata. The MO2 sort button uses the same `masterlist.yaml` and `userlist.yaml` as LOOT.

**Comment by MacSplody** [comment]
@Jeoshua Done, thanks for reporting it.
