### ISSUE TITLE
Darker Nights should be sorted after patched plugins since 1.11

### ISSUE THREAD

**Issue by unforbidable** [loot/fallout4#18]
pokara06 reports at http://www.nexusmods.com

http://pastebin.com/Y1cJ2V9x

There is a circular dependency right now because since version 1.11 plugin DarkerNights.esp may contain merged patches, i.e. it may have TrueStormsFO4.esp as a master now. The quickest solution is to remove ANY DarkerNights.esp master list entries.

Is it possible to add a general rule to sort DarkerNights.esp after all weather mods except plugins which have DarkerNights.esp as a master (standalone patches)?

I am the original submitter of the pull request  #3  and I can prepare another pull request when I set up my GitHub again and when you decide on how to proceed. Thank you

**Comment by Ortham** [comment]
> Is it possible to add a general rule to sort DarkerNights.esp after all weather mods except plugins which have DarkerNights.esp as a master (standalone patches)?

No, it's not. As for how to proceed, you know more about the problem than I do, so just submit a PR with whatever solution you choose.

**Comment by Ortham** [comment]
Closing this as the related PR has been merged.
