### ISSUE TITLE
Wrong/Out of Date CRC Data for Better Locational Damage Far Harbour plugin

### ISSUE THREAD

**Issue by Superfly-Johnson** [loot/fallout4#196]
Better Locational Damage - DLC_Far_Harbor.esp:
![Better Locational Damage - DLC_Far_Harbor.esp
](https://i.imgur.com/TOQIga3.png)

CRC is 0x647CE531, same as the one who is said to be dirty in the masterlist. This could be due to an update in FO4Edit

Pretty minor thing but I just noticed it while cleaning my plugins.

**Comment by Infernio** [comment]
So I recleaned them with xEdit 4.0.3f, and `Better Locational Damage - DLC_Far_Harbor.esp` is definitely dirty. `DLC03_UnarmedAngler "Unarmed Angler" [WEAP:01028203]` is an ITM.

**Comment by pStyl3** [comment]
Thanks for reporting the issue and the PR.
