### ISSUE TITLE
NX Pro Farming

### ISSUE THREAD

**Issue by Kronix420** [loot/fallout4#2]
http://www.nexusmods.com/fallout4/mods/2905

Problem arises as NX Pro Farming is updated from 1.54 to 1.6 here:
[NX Pro Farming](http://www.nexusmods.com/fallout4/mods/2905)

He has changed the file names, and LOOT is not sorting them at all now, and throws a master file error for two of the secondary files:

> NX Pro Farmer - Harvest Overhaul.esp  9F29108D
> This plugin requires "NX Pro Farmer.esp" to be installed, but it is missing.
> 
> NX Pro Patch - Homemaker+SSEx.esp  70D90BF8
> This plugin requires "NX Pro Farmer.esp" to be installed, but it is missing.

These sit last in sort order:

> NX Pro - Farm Core.esp  D8C9D382
> NX Patch - Homemaker.esp  9B63BF76
> NX Pro - Harvest Core.esp  64ECA8C1
> NX Patch - Safe SSEx.esp  C87D0073

---

Suggested load order:

> NX Pro - Farm Core.esp
> NX Pro - Compost Core.esp (optional)
> NX Pro - Harvest Core.esp (optional)
> NX Pro - Water Core.esp (optional)
> 
> **with Homemaker:**
> _Homemaker.esm_
> NX Pro - Farm Core.esp
> NX Pro - Compost Core.esp (optional)
> NX Pro - Harvest Core.esp (optional)
> NX Pro - Water Core.esp (optional)
> _(any other Homemaker patches go here)_
> NX Patch - Homemaker.esp

**Comment by Ortham** [comment]
> He has changed the file names, and LOOT is not sorting them at all now, and throws a master file error for two of the secondary files:

These plugins must be broken then, because LOOT is extracting that requirement from the plugins themselves. The plugins mentioned aren't present in the masterlist.

**Comment by Kronix420** [comment]
Thank you for the reply. Seems to be working perfectly for me now, and I'm testing with well over 100 mods.
