### ISSUE TITLE
Loot doesnt see any mods

### ISSUE THREAD

**Issue by mrenfrew** [loot/fallout4#23]
I had Loot installed and it was working great. Then messed up my game and had to uninstall everything and when I reinstalled Loot, it sees Fallout 4 and the add ons but when i download a mod from nexus with Nexus Mod manager, it does not see the mods at all. After reading posts and troubleshooting, I looked at my ini files, ran as administrator,verified my game files on steam,someone said it was a missing  C++ ,so I went to the site and downloaded what they suggested, I tried emptying the %localapp% thing. Im sorry If I dont know all the correct terms. Ive only been modding a short while. I did watch all of Gophers videos, some of them several times and read about issues and bugs, i just dont know what else to try.Im using windows 7, Steam is located in C/programs (x86) , and Nexus and 7-zip are on C\games if that makes a difference. the first time i used winzip the second i used 7-zip.  Im not sure if i correctly unpacked the zip files, i wasnt sure which one of the files to use except the two that were tar.xz where the instructions said dont use with windows.  Im sorry i put in so much info I wanted to provide enough  to descibe problem.

**Comment by Ortham** [comment]
Check fallout 4's data folder to see if the mods you think you've installed are actually in there.

**Comment by mrenfrew** [comment]
It started working again, Thank goodness.I was wondering how I was going to manage all my mods for my Mall of New America and zoo..I just wish I knew why it sudenly decided to work. Thank You for your help and time.
