### ISSUE TITLE
Masterlist update error

### ISSUE THREAD

**Issue by QuickTwist** [loot/fallout4#24]
I have a small problem with Loot. I get this message that says "An error occurred while trying to read information on the update masterlist. If this error happens again, try deleting the ".git" folder..." I tried deleting the git folder and I still get the message every time trying to update the master list. I believe it applies to Fallout 4 and not SSE.

[CEFDebugLog.txt](https://github.com/loot/fallout4/files/585074/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/585075/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
_I've edited the description and title to include what you posted in the forum thread._

Somehow you're trying to update using the wrong masterlist, so it's seeing a syntax error and rolling back through the entire history looking for a version that will work, but of course it never finds one. To fix this, open your LOOT settings and change the "Masterlist Repository Branch" for Fallout 4 (and any other games) to `v0.10`.

**Comment by QuickTwist** [comment]
I see. So could the problem be because I have more than one application of
Loot on my PC? I saw that that is what Gamer Poets does, so I was trying to
emulate him.

**Comment by Ortham** [comment]
Yes, all copies of LOOT use the same settings folder, so if you have multiple copies (which doesn't have any advantage over just using one), they all affect each other and so must all be the same version.

**Comment by QuickTwist** [comment]
I tried deleting all the files I could find from Loot and doing a fresh
install. I managed to uninstall it finding all the locations that it
existed, but now my Loot application doesn't automatically detect my
Fallout 4 game.

I apologize for taking up so much of you time, but if you can help me with
this, I would really appreciate it.

**Comment by QuickTwist** [comment]
NVM. I got it figured out. Just had to run the Fallout 4 exe.
