### ISSUE TITLE
LOOT leaves DLC plugins/esm unchecked in NMM since v0.10.1

### ISSUE THREAD

**Issue by NooBzPoWaH** [loot/fallout4#25]
Hello,
i've done a bit of research but all i could find was crash bug related, so i thought i might ask for your advice or let you know.
Since v0.10.1 (same with v0.10.2), after having sorted the plugins with LOOT the last four DLCs get unchecked in Nexus Mod Manager (and all the plugins having them as a master get orange of course), those are DLCCoast.esm, DLCworkshop02.esm & 03.esm & DLCNukaWorld.esm. 
Loot sees them still as active plugins though, even if i close it and run it again leaving them unchecked.

After coming over here i took a look at my CEFDebugLog which says : 
"Could not load cef_extensions.pak"
So i got it here on [github](https://github.com/AtomicGameEngine/CEF3Binaries/blob/master/Linux/Resources/cef_extensions.pak) and put it in the LOOT folder but same result with an empty CEFDebugLog.
 
So here are the debug logs from v0.10.2 without cef_extensions.pak installed : 
[CEFDebugLog.txt](https://github.com/loot/fallout4/files/629012/CEFDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/629013/LOOTDebugLog.txt)

I'm used to update LOOT (and BOSS before it) and i read changelogs and so on but i must have missed something here (hoping it's nothing too obvious, i'd hate to disturb you for something gone over a hundred times already like or stated in big red letters somewhere...).
I'm quiet happy using the v0.10 for now and i've got to thank you for all the support provided over the years, modding games would be a pain in the neck without you guys !
Cheers !

**Comment by Ortham** [comment]
It's an NMM bug, there should be an update available that fixes it.

**Comment by NooBzPoWaH** [comment]
All right then it's on my side, i didn't update NMM because i'm afraid it messes up with all my mods installed.
Last time i did it i got mostly all of my Skyrim's Mods uninstalled, so i thought i'd wait until the end of my current playthrough.
Thanks for such fast reply !
