### ISSUE TITLE
Radrose Update 3.0.1 Dependency Warnings

### ISSUE THREAD

**Issue by DaCoolX** [loot/fallout4#255]
So [Radrose Usability Enhancements](https://www.nexusmods.com/fallout4/mods/18098) had an update, the `Radrose Usability Enhancements.esp` had its `.esp` extension changed to `.esm` showing warnings of unfulfilled dependencies and the like for related patches.

**Comment by MacSplody** [comment]
@DaCoolX Done & thanks for reporting it.
