### ISSUE TITLE
Sim Settlements 2 and Extended Dialogue Interface require a patch

### ISSUE THREAD

**Issue by spaceoden** [loot/fallout4#263]
There's a patch needed for Sim Settlements 2 (SS2.esm) and Extended Dialogue Interface (XDI.esm) available here: https://www.nexusmods.com/fallout4/mods/48254
It would be nice if LOOT notified when the patch is absent from the load order as it does for some other mods/patches.
Currently the patch appears in 3 forms: "SS2_XDI Patch.esp", "SS2_XDI Patch-Basic.esp" and "SS2_XDI Patch-Basic_esl.esp". If any one of these plugins is present on the load order then there's no need to notify about a missing patch.
I might try to PR it myself, but I have to learn the new masterlist syntax.

**Comment by sibir-ine** [comment]
@spaceoden Here are the [docs](https://loot-api.readthedocs.io/en/stable/metadata/introduction.html) on the current metadata syntax. Don't worry about getting it 100% right the first time either; we're happy to provide tips & corrections. We can add the message ourselves if you prefer though.

**Comment by spaceoden** [comment]
I went ahead a took a stab at it via #264
