### ISSUE TITLE
FirstPersonViewableItemsExpanded use %1% version

### ISSUE THREAD

**Issue by TheRealArchie** [loot/fallout4#269]
FirstPersonViewableItemsExpanded has a warning when installed:

> Use %1% version.

What does this mean?

**Comment by sibir-ine** [comment]
Looks like a typo prevented text from getting subbed into the `%1%` part. I'll fix that in a moment, thanks for reporting it!

**Comment by sibir-ine** [comment]
@TheRealArchie Fixed, please update your masterlist.
