### ISSUE TITLE
 "[0104/150045:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak"

### ISSUE THREAD

**Issue by Elfere** [loot/fallout4#27]
okay, here goes. latest loot 10.2, up to date fallout4 with DLCs. loot was previously working. now i'm getting "[0104/150045:ERROR:main_delegate.cc(752)] Could not load cef_extensions.pak" nothing is 'read only', i've uninstalled and reinstalled + reset. plus delteing the %username app data% loot loads fine, crashes on sort.

tried installing both in the fallout directory (D:\) and the default C:\ (always with uninstall procedures followed - deleteing %user app% resetting etc..

[CEFDebugLog.txt](https://github.com/loot/fallout4/files/685865/CEFDebugLog.txt)

no other files created unfortunately!

**Comment by Ortham** [comment]
That error is harmless.

**Comment by Elfere** [comment]
its as i feared... the crash is happening without giving me any useful information for you...Is there someway i can get windows to pump out an error msg for you?

**Comment by Ortham** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by MythrilBoomstick** [comment]
I've gotten the same error message and have been unable to sort my mods correctly with many of the mods in an incorrect order, not sure if it's the issue but it seemed to be fine before this.
[CEFDebugLog.txt](https://github.com/loot/fallout4/files/722487/CEFDebugLog.txt)

**Comment by MythrilBoomstick** [comment]
still not sure what else i could send to help

**Comment by MythrilBoomstick** [comment]
[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/722494/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
> I've gotten the same error message and have been unable to sort my mods correctly with many of the mods in an incorrect order, not sure if it's the issue but it seemed to be fine before this.

As I've already said, the `Could not load cef_extensions.pak` error is harmless, and @Elfere was reporting a crash, not incorrect sorting, please don't hijack other issue threads. Create a new issue and describe in detail exactly what you think is wrong with the sorted load order.

**Comment by Ortham** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT.
