### ISSUE TITLE
MO2 and LOOT: LOOT Now Disables FO4 and all DLC .esm Files with MO2

### ISSUE THREAD

**Issue by aBlazeOfGlory** [loot/fallout4#29]
I play Fallout 4 with the season pass/all DLC and use Mod Organizer 2 for my mod manager. I use MO2 and launch the game with F4SE in MO2. I always update LOOT as soon as I see a new version was released and the last 2 or 3 versions of LOOT cause problems with MO2. Every single time I sort my load order with LOOT and go back to MO2, it has sorted my load order but it automatically disables the Fallout and DLC .esp and .esm files at the top. I have to manually enable them every time. But for some reason, when I then launch Fallout 4, it still says those files are disabled. I try to load my last save in Fallout 4 and get the error message saying that the files are missing  "Fallout4.esm, DLCCoast.esm, DLCNukaWorld.esm, DLCRobot.esm, DLCworkshop01.esm, DLCworkshop02.esm, and DLCworkshop03.esm are missing, even though I enabled them in MO2 before launching the game through F4SE. Basically, any of the plugins at the top in bold italics are missing/disabled. I never had this problem with older versions of LOOT and don't know why it started happening after the last two or three updates of LOOT. If you could please fix this so I can use MO2, LOOT, and F4SE again, I would REALLY appreciate it. Thank you.

If anyone knows where I can download older versions of LOOT, please let me know!

**Comment by Ortham** [comment]
It's a bug in MO2.
