### ISSUE TITLE
Masterlist Unmodified - Master Files at bottom of load order

### ISSUE THREAD

**Issue by QuickTwist** [loot/fallout4#293]
Hi.

IDK what I did wrong by my master files are at the bottom of my load order in the plugins section of Vortex. I've tried to reset the masterlist, but that is when I get the error.

I did try and download LOOT because I didn't know that Votex comes with LOOT already. This might have messed things up, but now IDK how to fix it.

Edit: This is for Skyrim SE, not Fallout. Sorry, it just brought me here for some reason.

**Comment by MacSplody** [comment]
> 
> 
> Hi.
> 
> IDK what I did wrong by my master files are at the bottom of my load order in the plugins section of Vortex. I've tried to reset the masterlist, but that is when I get the error.
> 
> I did try and download LOOT because I didn't know that Votex comes with LOOT already. This might have messed things up, but now IDK how to fix it.
> 
> Edit: This is for Skyrim SE, not Fallout. Sorry, it just brought me here for some reason.

Well it's not a LOOT issue, so I'll close this.

---

But, try changing your UI settings in Vortex, that might be the issue..

![image](https://user-images.githubusercontent.com/1944639/132434498-0e0e8dfb-e197-4871-89ce-9936cbf5d000.png)

![image](https://user-images.githubusercontent.com/1944639/132434673-bd289b94-4bca-4582-a567-20639ec3a0c7.png)
