### ISSUE TITLE
Previs Repair Pack

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout4#322]
[Previs Repair Pack](https://www.nexusmods.com/fallout4/mods/46403/)

> Compatibility:
> ~~Same rules as any other mod that affects precombines. Load order suggestion is just after UF4OP, unless you have to override other mods, then lower it as needed.~~ Load order advice has changed as follows: Roughly 85-90% towards the bottom of your load order, depending on the mods that change interior / exterior cells. Doing this resolves most of the easy conflicts due to how headers work for precombines. If you still have issues after this and aren't using something like BTInteriors and other well known conflicting mods, report a bug or ask in the usual places as noted below.

Could be grouped after `default`, which would cover "Roughly 85-90% towards the bottom of your load order".
The main issue is. which mods need to be loaded after PRP?

---

Incompatible with:
[Boston FPS Fix - aka BostonDT PreVis-PreCombine](https://www.nexusmods.com/fallout4/mods/26286/)
[FROST Survival Simulator](https://www.nexusmods.com/fallout4/mods/18898/) - Use [FROST - Interior Cell Fixes](https://www.nexusmods.com/fallout4/mods/48425/) and [FROST - Exterior Cell Fixes and FPS Boost](https://www.nexusmods.com/fallout4/mods/54950/) instead.

---

Load after:
Currently in groups NPC & Faction Overhauls
`SuperMutantRedux.esp`
`Unique NPCs.esp`
`Unique NPCs - Creatures and Monsters.esp`

Currently in groups Items
`Weaponsmith Extended 2.esp`

![image](https://user-images.githubusercontent.com/1944639/138582144-35bf011e-c13c-46fd-98ac-358df0614726.png)

**Comment by Diskmaster** [comment]
Re: Frost, add https://www.nexusmods.com/fallout4/mods/54950 as well as per their current loadlist over there.

Also am mod dev.

**Comment by MacSplody** [comment]
Some conflicts with `Weaponsmith Extended 2.esp`

Only changes carried forward by WSE2 from DLC.
![image](https://user-images.githubusercontent.com/1944639/138220717-23299d67-79ee-410f-ae7e-7a119d1d7d93.png)

PRP after WSE2 would be optimal.
![image](https://user-images.githubusercontent.com/1944639/138220325-b94e40f7-eda1-47b4-b7d8-8610beddd1b5.png)

---

`Unique NPCs.esp` reverts changes
No conflicts if order is reversed.

![image](https://user-images.githubusercontent.com/1944639/138225402-c54b0976-b52b-4edf-ba81-9bf3e4521c90.png)

---

`Unique NPCs - Creatures and Monsters.esp`
PRP after it would be optimal.
![image](https://user-images.githubusercontent.com/1944639/138221473-c1a9425c-73d9-4caa-b93d-7768b99213e5.png)

---

`SuperMutantRedux.esp` reverts changes
No conflicts if order is reversed.

![image](https://user-images.githubusercontent.com/1944639/138225262-36d752bc-af7c-4836-92e7-1cea2c49dde7.png)

![image](https://user-images.githubusercontent.com/1944639/138225146-c4d39241-8372-4e26-bcce-0aa674e3717e.png)

---

No conflicts with:
`Armorsmith Extended.esp`

**Comment by MacSplody** [comment]
Interior lighting mods would require a patch.
Some provided on mod page.

---

`UltraInteriorLighting.esp` with `PRP-Compat-UIL.esp.
Still some unresolved conflicts.

![image](https://user-images.githubusercontent.com/1944639/138670683-7fe8b58e-5ee8-4895-aac7-723918da7fed.png)

`UltraInteriorLighting.esp` and `PRP.esp` are not master files for `PRP-Compat-UIL.esp.
So we have no idea which order the patch was made for.

![image](https://user-images.githubusercontent.com/1944639/138670963-3f93d70b-937b-40ab-98d7-17965848e424.png)

---

[Enhanced Lights and FX](https://www.nexusmods.com/fallout4/mods/13596/) and [Optimization Patches Collection](https://www.nexusmods.com/fallout4/mods/54872/) replacement plugin.
`EnhancedLightsandFX.esp`

![image](https://user-images.githubusercontent.com/1944639/138582760-ea0c10e2-78ed-475e-8d4b-8fe2114c66cb.png)

![image](https://user-images.githubusercontent.com/1944639/138582779-ffe55014-0dee-4aa7-b5ff-d95835169d76.png)

ELFX does revert more changes.
![image](https://user-images.githubusercontent.com/1944639/138586665-fdb6eea9-d012-4c06-bbd1-041fb78e5b86.png)
