### ISSUE TITLE
LOOT still needs to be done manually

### ISSUE THREAD

**Issue by modses1420** [loot/fallout4#33]
![2017-02-04 1](https://cloud.githubusercontent.com/assets/22419373/22616865/edeb469e-ea73-11e6-88b4-50add427e390.png)
It never puts Scrap All at the bottom, like it should, which makes me wonder what other mistakes it makes.

**Comment by Freso** [comment]
Why do think Scrap All should be at the bottom? (Did you read the FAQ entry ["I'm suspicious that LOOT is ordering plugin X after plugin Y. How do I double-check the ordering?"](https://loot.github.io/docs/help/LOOT-FAQs.html#check-the-ordering)?) Can you please put a link to the mod(s) you feel are getting sorted wrong?

Currently it seems like [we only have `Scrap Everything.esp` in the masterlist](https://github.com/loot/fallout4/blob/94992bcd68991210f6443a36afeffc1aeb02ccae/masterlist.yaml#L889), so the ones you've highlighted wouldn't get any special treatment from LOOT and thus be sorted [entirely based on their contents](https://loot.github.io/docs/help/LOOT-FAQs.html#unrecognised-plugins).

**Comment by Ortham** [comment]
Not sure why I assigned this to me or marked it as an app issue, undoing that...

**Comment by Freso** [comment]
No reply from @modses1420 since February. Closing this issue. It can be reopened later, or new tickets can be filed.
