### ISSUE TITLE
Sanctuary Reworked Roads

### ISSUE THREAD

**Issue by mightyzog** [loot/fallout4#36]
Fallout 4 
Masterlist Revision	1db0851

Sanctuary Reworked Roads http://www.nexusmods.com/fallout4/mods/23051/? is sorted too high in the load order in relation to Sanctuary Residences Rebuild Basic http://www.nexusmods.com/fallout4/mods/23131/?

  0  0 Fallout4.esm
  1  1 DLCRobot.esm
  2  2 DLCworkshop01.esm
  3  3 DLCCoast.esm
  4  4 DLCworkshop02.esm
  5  5 DLCworkshop03.esm
  6  6 DLCNukaWorld.esm
  7  7 Unofficial Fallout 4 Patch.esp
  8  8 ArmorKeywords.esm
  9  9 HUDFramework.esm
 10  a SpringCleaning.esm
 11  b EthreonMasterPlan.esp
 12  c SimSettlements.esm
 13  d CROSS_CosmeticFramework.esm
 14  e Reverb and Ambiance Overhaul.esp
 15  f AshGooPilesAwayV1.3.esp
 16 10 Scrap-able Mods - AllinOne+DLC - Vanilla.esp
 17 11 WeaponModFixes.esp
 18 12 Autocorrect.esp
 19 13 Companion Infinite Ammo.esp
 20 14 free_downgrades.esp
 21 15 FreshLookDesdemona.esp
 22 16 FreshLookEllie.esp
 23 17 FreshLookMagnolia.esp
 24 18 FreshLookMaxson.esp
 25 19 FreshLookHaylen.esp
 26 1a GruffyddsSignsAndPosters.esp
 27 1b Insignificant Object Remover.esp
 28 1c LifeGiverRadRemove.esp
 29 1d LongerPowerLines2x.esp
 30 1e Lots More Facial Hair.esp
 31 1f Lots More Female Hairstyles.esp
 32 20 Lots More Male Hairstyles.esp
 33 21 FIXEDGoodfeels_no_DLC_needed.esp
 34 22 ModdableGoodfeels.esp
 35 23 NoBOSVertibirdRandomEncounters.esp
 36 24 No Enemies or Locations on Compass.esp
 37 25 NSA All-in-One.esp
 38 26 fix_Perk_CombatMedic.esp
 39 27 Realistic Death Physics.esp
 40 28 RealisticHuntingRifle.esp
 41 29 dD-Realistic Ragdoll Force.esp
 42 2a dD-Reduced Explosion Force.esp
 43 2b Recruitable NPC Dialogue Fixes.esp
 44 2c RestaurantsGiveFood_Vanilla.esp
 45 2d ScrapDeadThings.esp
 46 2e SteadyAimChange.esp
 47 2f Mole Rat Disease Fix.esp
 48 30 WeaponModFixes-Automatron.esp
 49 31 WMF-A-Patch-AWKCR.esp
 50 32 CBBE.esp
 51 33 CompanionAccuracy.esp
 52 34 Companions GPS.esp
 53 35 CompanionsGoHome_A.esp
 54 36 Craftable Vault 81 Cure (Earned).esp
 55 37 CraftableAnimationMarkers.esp
 56 38 Extended weapon mods.esp
 57 39 ProvisionerBackPack.esp
 58 3a Northland Diggers New.esp
 59 3b Better Artillery Flares (zero weight version).esp
 60 3c Faction Field Outfits.esp
 61 3d Fat Man Removal.esp
 62 3e infinite_settlement_budget.esp
 63 3f NoWildFruit.esp
 64 40 SoundOfSilence-No_Events_music.esp
 65 41 SoundOfSilence-E.esp
 66 42 Lasers Have No Recoil.esp
 67 43 MinigunGyroRecoil.esp
 68 44 ReducedRocketRecoil.esp
 69 45 Immersive HUD.esp
 70 46 Armorsmith Extended.esp
 71 47 EndorsCustomCombatArmor.esp
 72 48 Armorsmith All DLCs Patch.esp
 73 49 The Rebel Tex-Edits Standalone Crafting.esp
 74 4a Trading Stand Perk Requirement.esp
 75 4b Gunplay.esp
 76 4c Eli_ArmourCollection.esp
 77 4d Emergent Properties.esp
 78 4e DD_TRUMP_2016_MAKE_MODDING_GREAT_AGAIN.esp
 79 4f SoundOfSilence-No_HP_Noise.esp
 80 50 BTInteriors_Project.esp
 81 51 NAC-PRC.esp
 82 52 RaiderOverhaul.esp
 83 53 MaterialSwapFixes-Combined.esp
 84 **54 [777] Sanctuary - Reworked Roads.esp**
 85 55 UnlockedTrailersProject[UTP]v2.0.esp
 86 56 SuperMutantOverhaul.esp
 87 57 More Smarter Companions Mod.esp
 88 58 FreshLookCait.esp
 89 59 FreshLookDanse.esp
 90 5a FreshLookDeacon.esp
 91 5b FreshLookMaccready.esp
 92 5c FreshLookPiper.esp
 93 5d WET Clearer.esp
 94 5e No Companion Junk Comments.esp
 95 5f dD-Enhanced Blood.esp
 96 **60 [777] Sanctuary - Modern Residences Rebuild - Basic.esp**
 97 61 Boston Pirate Radio.esp
 98 62 Mercenary.esp
 99 63 FreshLookGlory.esp
100 64 WeaponDamagesFixed.esp
101 65 Armorsmith Elianora.esp
102 66 Eli_RuggedOutfits.esp
103 67 BetterStores.esp
104 68 PipPOD.esp
105 69 DWT_TrashcanCarla_and_Guards.esp
106 6a JetfuelRadio.esp
107 6b Primez Military Fatigues.esp
108 6c Armorsmith L0rdOfWar.esp
109 6d DV-Very Durable Vertibirds.esp
110 6e DV-Armored Pilots.esp
111 6f DV-No Levelled Vertibirds.esp
112 70 DiamondCitySWAT.esp
113 71 Guard Rug - D3.esp
114 72 Guard Rug - D6.esp
115 73 Guard Rug - D1.esp
116 74 Guard Chair - D3.esp
117 75 Guard Chair - D6.esp
118 76 Guard Stool - D3.esp
119 77 Guard Stool - D6.esp
120 78 RenRadioMod.esp
121 79 Chops.esp
122 7a Strong Back - Improved -- Far Harbor.esp
123 7b TransferSettlements.esp
124 7c No Audiofilters on the Radio 0.4.esp
125 7d SC_ExpandedBuildings.esp
126 7e SC_ExpandedConcrete.esp
127 7f SC_ExpandedDirtGrass.esp
128 80 SC_ExpandedHedges.esp
129 81 SC_ExpandedLanterns.esp
130 82 BetterSettlersNoLollygagging.esp
131 83 BetterSettlers.esp
132 84 BetterSettlersFarHarborPatch.esp
133 85 BS NS Merged Patch.esp
134 86 EferasBetterBeds.esp
135 87 VanillaExtensions.esp
136 88 BetterJunkFences.esp
137 89 Crimsomrider's Tomb Raider Accessories.esp
138 8a DD_why_am_i_doing_this.esp
139 8b KSHairdos.esp
140 8c Crimsomrider's Unique Furniture.esp
141 8d Crafting Workbench.esp
142 8e Crafting Workbenches - Ammo.esp
143 8f Crafting Workbenches - Ammo Special.esp
144 90 Crafting Workbenches - Automatron DLC.esp
145 91 Crafting Workbenches - Faction and Quest Requirements.esp
146 92 Crafting Workbenches - Pre War and Manufactured.esp
147 93 ImmersiveScrapping_SeasonPass.esp
148 94 ImmersiveScrapping.esp
149 95 MacCready's Wooden Soldier Toy is No Junk! (No sorting mod).esp
150 96 HZS Easy Homebuilder and Working Double Beds.esp
151 97 BetterShackBridges.esp
152 98 WoodenPrefabsExtended.esp
153 99 SMH.esp
154 9a Valentine_Armored_Detective.esp
155 9b Siles - Connectable Electricpoles.esp
156 9c Companion Fall Damage Immunity.esp
157 9d BrahminFeederFull.esp
158 9e MTM-NoGreenWeather.esp
159 9f NAC-PRC Nucleartime.esp
160 a0 NAC-PRC Summertime.esp
161 a1 NAC-PRC Wintertime.esp
162 a2 NAC-PRC-NukaWorld.esp
163 a3 NAC-PRC-FarHarbor.esp
164 a4 NPCUseRailings.esp
165 a5 GunSmoke.esp
166 a6 Raider Overhaul - AE Patch-Restored Content.esp
167 a7 Raider Overhaul - AE Patch.esp
168 a8 Survivalist Go-Bags_AE_AWKCR.esp
169 a9 WindowBoards.esp
170 aa AnS Wearable Backpacks and Pouches.esp
171 ab AnS Wearable Backpacks and Pouches - Ballistic Weave.esp
172 ac AnS Wearable Backpacks and Pouches - Power Armor Carry Capacity.esp
173 ad Fishers.esp
174 ae ProvisionerSupplyContainers.esp
175 af SniperDamage.esp
176 b0 Tactical Flashlights.esp
177 b1 Tactical Flashlights - Settings.esp
178 b2 Pip-Boy Flashlight.esp
179 b3 SpotlightShadows.esp
180 b4 Prefabs.esp
181 b5 CR_OuthouseCollection.esp
182 b6 PipeGalore.esp
183 b7 BoxHouses.esp
184 b8 SLR.esp
185 b9 CabinInTheWoods.esp
186 ba Vanilla Settler Replacements.esp
187 bb CookingStationsProduceFood.esp
188 bc Swinging Meat Bags.esp
189 bd More Realistic Cats.esp
190 be AzarPonytailHairstyles.esp
191 bf Sandbag Fortifications - Version 2C.esp
192 c0 DWT_Cricket_and_Guards.esp
193 c1 DWT_DocWeathers_and_Guards.esp
194 c2 SalvageBeacons.esp
195 c3 RU556.esp
196 c4 WestTekTacticalOptics.esp
197 c5 Skibs-WH77Redux.esp
198 c6 GrenadeLauncherStandalone.esp
199 c7 CROSS_Uni_Headset.esp
200 c8 NCMC.esp
201 c9 Faction Field Outfits Level List.esp
202 ca CROSS_Uni_Headset_LeveledLists.esp
203 cb SimSettlements_AddOnPack_Utilities_JtBryant.esp
204 cc IncreasedSettlerPopulation20.esp
205 cd AkaSinger.esp
206 ce AkaSingersWardrobe.esp
207 cf BS-ExtraCustomProps.esp
208 d0 BS-FarHarborExpansion.esp
209 d1 BrighterSettlementLights_LongAndSoft.esp
210 d2 SpotlightFix-100-Shadow.esp
211 d3 RC_BarnSet.esp
212 d4 LooksMenu.esp
213 d5 LooksMenu Customization Compendium.esp
214 d6 DansesHolotagsArentScrap.esp
215 d7 ScrappableBandanas.esp
216 d8 LootandScrap.esp

**Comment by Ortham** [comment]
So `[777] Sanctuary - Reworked Roads.esp` is supposed to load after `[777] Sanctuary - Modern Residences Rebuild - Basic.esp`?

**Comment by mightyzog** [comment]
actually I don't think it is modern residences that it needs to go after. I tried that and the roads reset to the default. it only works for me if I have it near the bottom of the load order.

sorry for the delay in replying, I was too busy playing the game to check my emails :S

**Comment by Ortham** [comment]
Closing this as invalid, since the issue doesn't seem to be as described.
