### ISSUE TITLE
Always put new mods in the last

### ISSUE THREAD

**Issue by AlexBorquezIV** [loot/fallout4#39]
I don't know why is doing this put I see theres someone with the same problem and I think can be the update of the mods and the new ones

**Comment by adamnorbacker** [comment]
I agree with this. It doesnt work anymore as it doesnt sort the mods no more. All it did was put it before bashed patch. 

Started as administrator and no firewall issues, windows 10 64-bit.

**Comment by Ortham** [comment]
Could you give specific examples of plugins that are being sorted incorrectly?

Please also see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html).

**Comment by adamnorbacker** [comment]
Every plugin. I moved my NMM virtual folder to another drive so i reinstalled my mods. Those that wasnt installed by nmm stayed where they were while the reinstalled were put after those.

It could be a application issue by the latest huge update for windows 10 as it doesnt sort any popular mod...
Anyway as I said, it happens with new installed mods, doesnt matter if it is CBBE, dD-Enhanced Blood or any other famous mod.

The nmm mods is from chem_redux.esp and below
link to img of loadorder: http://i.imgur.com/NoskJe7.png

**Comment by Ortham** [comment]
By specific examples, I mean how do you know the plugins that aren't getting moved should be? Your Bashed Patch still getting put after the newly installed mods suggests everything is still working. 

I'm guessing that what is happening is that NMM is installing the mods and appending them to your load order, then when LOOT runs it sees no reason to move them, and leaves them there. If this is wrong, there's either something wrong with LOOT's logic (unlikely), or the plugins just need metadata added, but the absence of change does not indicate that there is an issue.

**Comment by AlexBorquezIV** [comment]
I see because a few minutes I try to order settlements objects expancion pack with nmm and other with bethesda.net and doesn't order that mod in the last and that the mod is seem strong

**Comment by AlexBorquezIV** [comment]
I see the debug log location and it saying: [19:51:26] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[19:51:26] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700
What means?... Its your program maybe you know what mean

**Comment by Ortham** [comment]
> I see the debug log location and it saying: [19:51:26] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic
> [19:51:26] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700
> What means?... Its your program maybe you know what mean

Those warnings are harmless (and the behaviour they're warning about is actually intentional).

**Comment by AlexBorquezIV** [comment]
How?

**Comment by AlexBorquezIV** [comment]
First... who made this program?... you? Or one of your team?

**Comment by AlexBorquezIV** [comment]
Forget my cuestion... I ser that the problems are the mods not the loot... but thanks anyway
