### ISSUE TITLE
Low global_priority for broad texture overhauls

### ISSUE THREAD

**Issue by Freso** [loot/fallout4#40]
Mods such as [Optimized Vanilla Textures](http://www.nexusmods.com/fallout4/mods/1204/) and [FAR](http://www.nexusmods.com/fallout4/mods/20713) consist of "empty" plugins that are there just to facilitate loading .ba2 archives. I kind of want to give these mods (at least OVT) very low `global_priority`, maybe even to the tune of something like `-110`, putting them after official DLC plugins, but before (unofficial) patches (see [Global Priorities](https://loot.github.io/docs/contributing/Global-Priorities.html), to make sure more specific textures from smaller mods override these more wide reaching ones.

I wanted to try and get some feedback first though, before I start putting mods in such a low global priority "group". So any thoughts? Is this a silly idea?

**Comment by Ortham** [comment]
No idea, try it and see if anyone complains. 😛

**Comment by Freso** [comment]
Did it with https://github.com/loot/fallout4/commit/6eaef0be71c68b956fafa5cf27ce2037d70f467d - any complaints can be filed as new issues.
