### ISSUE TITLE
Error LOOTDebugLog.txt 

### ISSUE THREAD

**Issue by zp3nz3r** [loot/fallout4#41]
Whenever I sort my plugins in LOOT for Fallout 4 and click apply, an error text will prompt up saying "Error
Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information." I have no idea what this means. I opened the degub folder location and I don't know what to do. Please help. Also loot won't install

**Comment by Ortham** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html), that may help you.

**Comment by zp3nz3r** [comment]
Hi,

I cannot upload the required files because that would require loot to
successfully install. As I mentioned in my original email, this doesn't
happen for some reason. When Loot opens after the suppossed installation, I
try to sort my load order then click apply, but this error text comes up
every time. Then when I close Loot, I can't find it where Installed it, nor
is there a desktop shortcut.

**Comment by Freso** [comment]
You could still file it in the proper issue tracker (hint: it's not this one :wink:): https://github.com/loot/loot/issues

**Comment by Ortham** [comment]
> I cannot upload the required files because that would require loot to
> successfully install. 

You can't run LOOT at all if it didn't successfully install. You also don't need to run the installer to use LOOT, it's also available as a plain archive.

> Then when I close Loot, I can't find it where Installed it, nor
> is there a desktop shortcut.

I think the option to add a desktop shortcut in the installer is unticked by default? Anyway, it doesn't matter, because the installer adds an entry to your Start menu/screen's application list.

**Comment by zp3nz3r** [comment]
Posted a new report [https://github.com/loot/fallout4/issues/44](url) with a better explanation as to what happened and uploaded the following files;

[CEFDebugLog.txt](https://github.com/loot/fallout4/files/1133731/CEFDebugLog.txt)
[LOOTAPIDebugLog.txt](https://github.com/loot/fallout4/files/1133733/LOOTAPIDebugLog.txt)
[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/1133735/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
:man_facepalming: You could have just edited the OP, and you've filed the new issue in the wrong tracker again. Closing this as a duplicate.
