### ISSUE TITLE
Tactical Tablet

### ISSUE THREAD

**Issue by Pickysaurus** [loot/fallout4#415]
Please add a warning when `TacticalTablet.esp` is loaded alongside `AutoUnequipPipboy.esp`, `HidePipboy.esp`, `Pipboy Zero.esp`, or `PipboyRemover.esp` to tell the user these mods are not compatible and should not load together.

Thanks

**Comment by sibir-ine** [comment]
@Pickysaurus Can you please link to those five mods?

**Comment by Pickysaurus** [comment]
Main mod: https://www.nexusmods.com/fallout4/mods/55346?tab=files

AutoUnequipPipboy : https://www.nexusmods.com/fallout4/mods/15342?tab=files (Seems like it may actually be an ESM)
HidePipboy: https://www.nexusmods.com/fallout4/mods/805?tab=files
Pipboy Zero: https://www.nexusmods.com/fallout4/mods/6078?tab=files
PipbodyRemover: https://www.nexusmods.com/fallout4/mods/13603?tab=files

**Comment by sibir-ine** [comment]
@Pickysaurus Thanks for the report! I added `AutoUnequipPipboy.esm` instead of `AutoUnequipPipboy.esp` as the ESP version doesn't seem to be available anymore.
