### ISSUE TITLE
Change license to Creative Commons Zero

### ISSUE THREAD

**Issue by Freso** [loot/fallout4#42]
I would like to relicense the Fallout 4 masterlist/repository to be under the [Creative Commons Zero license](https://creativecommons.org/publicdomain/zero/1.0/) (effectively submit it to the public domain). See https://github.com/loot/loot.github.io/issues/61 for more thoughts on this.

Obviously I give consent myself, but while I'm the main contributor to the FO4 masterlist, I'm not the only one: @Sharlikran, @WrinklyNinja, @unforbidable, @ghostsquad, @darthbdaman, @icopp, @thurask, @ExE-Boss, @sehraf, @yetihairball, @Loganbacca, @shadowslasher410, @DiglidiDudeNG if you agree with moving to this much more free license, please write a comment confirming this.

- [x] @Freso
- [x] @Sharlikran
- [x] @WrinklyNinja
- [x] @unforbidable
- [x] @ghostsquad
- [x] @darthbdaman
- [x] @icopp
- [x] @thurask
- [x] @ExE-Boss
- [x] @sehraf
- [x] @yetihairball
- [x] @Loganbacca
- [x] @shadowslasher410
- [x] @DiglidiDudeNG

**Comment by Ortham** [comment]
I'm okay with this.

**Comment by icopp** [comment]
Sounds good to me.

**Comment by ElArGee** [comment]
No problems here 👍

**Comment by thurask** [comment]
Fine by me.

**Comment by darthbdaman** [comment]
No problem

**Comment by sehraf** [comment]
I'm ok with it

**Comment by ExE-Boss** [comment]
I’m also OK with this.

**Comment by unforbidable** [comment]
I approve of this.

**Comment by fdrobidoux** [comment]
I only recently started contributing but yes, I'm all for it.

**Comment by ghostsquad** [comment]
Sounds good to me!

**Comment by Sharlikran** [comment]
Go ahead

**Comment by shadowslasher410** [comment]
I'm okay with it, except we should probably make the other games' masterlists use the same license for simplicity's sake. That is, if everyone's okay with that.

**Comment by Freso** [comment]
Absolutely. I'm just starting with the masterlists with the fewest amount of involved people to get going. :)

**Comment by yetihairball** [comment]
Fine by me.

**Comment by Freso** [comment]
License has been changed! Thanks everyone!
