### ISSUE TITLE
Start Me Up Redux

### ISSUE THREAD

**Issue by redguar** [loot/fallout4#422]
As per [Start Me Up - Alternate Start and Dialogue Overhaul](https://www.nexusmods.com/fallout4/mods/18946)'s "Questions" section under "Are these other mods compatible with Start Me Up?"

> * COMPATIBLE, BUT PAY ATTENTION
>   * Horizon works for many people, but if you experience problems, try installing Start Me Up after you are out of the vault, or only using the Vault-Based Alternate Start option.
>   * The Pip-Pad mod: follow the instructions and only install it AFTER you are done with the Vault
>   * Same Sex Couples: put it after Start Me Up in your load order
>   * Main Quest Choices: put it after Start Me Up in your load order

So I believe [Horizon](https://www.nexusmods.com/fallout4/mods/17374) and [Pip-Pad Mod](https://www.nexusmods.com/fallout4/mods/21953) should try to get a warning message (so `Z_Horizon.esp` and `PIP-Pad.esp`)
And [Same Sex Couples](https://www.nexusmods.com/fallout4/mods/25254) and [Main Quest choices](https://www.nexusmods.com/fallout4/mods/19835) should automatically be sorted after Start Me Up.
So `SameSexFemale.esp`, `SameSexMale.esp`, `AFTOSforSSC.esp`, `SameSexFemale - ufpafdlcnh.esp`, `SameSexFemale -ufpafdlc.esp`, `SameSexFemale - ufpafnh.esp`, `SameSexFemale - ufpaf.esp`, `SameSexFemale - UP.esp`, `LGBT Family.esp`, `LGBT Family (2).esp`, `SameSexFemale - ufp.esp`, and `Spare Railroad as Institute.esp` should all automatically be sorted after. 

Thanks

**Comment by sibir-ine** [comment]
It looks like there's an [updated version](https://www.nexusmods.com/fallout4/mods/56984) officially endorsed by SMU's author, so I'll add an update message, compatibility messages, & load rules for the new version & see what still applies from the old version.

---
> Compatible, but requires some set-up :
> 
> Subversion - is compatible, use the holotape crafted in chem station to remove you-are-a-parent-related dialogues from the quest.
> 
> Nuka World Reborn/Viva Nuka World - is compatible in general playthrough, but you have to load Nuka World Reborn and Viva Nuka World after Start Me Up. The incompatibilities are quest logs which will be override and some script fragments override, this may or may not cause perceivable breakage in normal gameplay, but issues may still arise.
> 
> Sim Settlement 2 - is 'technically' compatible if you don't chose to level up during character creation, you have to start at level 1 only. However Sim Settlement 2 is not compatible in term of story as it forces you to be the concerned parent, which I am currently working on a patch for it.
> 
> If you stuck at Institute's Elevator when you get there the first time. Killable Children is well known to cause this, Don't use Killable Children, Use [Immersive Killable Children](https://www.nexusmods.com/fallout4/mods/8434/?) WITH [size fix](https://www.nexusmods.com/fallout4/mods/16586?tab=files) or [Mortal Youth](https://www.nexusmods.com/fallout4/mods/56224?tab=files). (and patch it if you use Shaun's Default Appearance plugin) This is not Start Me Up bug, check for mod conflicts. This is also a known vanilla bug that happens if you wear power armor into the institute the first time so don't.
> 
> Complex Sorter - Initially the 'Quest Tagging' option was not compatible with Start Me Up and causes bugs such as being stuck at Piper Interview. However, now a patch is provided for a workaround. (At the version 1.11.3+ of Complex Sorter - this patch is not needed anymore but just in case)
> 
> Player Comments and Head Tracking - Download the Player Comment Start Me Up Patch in the original Player Comments page and download Piper's Quest fix as provided it here. Load Piper Fix After Player Comments and Player Comments Start Me Up Patch. Piper Quest should work now.
> 
> Horizon - Needs a patch to play together without crashing and correcting SPECIAL and level calculation, I made a rough, improvisational patch for Horizon in optional download. However you cannot start with any extra gear as it'll crash the game while loading into Commonwealth - you can only choose 'only clothes on your back' choice.
> 
> Not Compatible : Other alternate start mods because obviously, Piper Interview Restored, Killable Children, Nora Spouse Companion, Dual Survivor Nate Companion, Amazing Follower Tweaks, quest mods that alter this game's main quests or game start sequences may not be compatible.
> 
> No main quest - Wasteland Operator mod - You won't get radios if you use this mod. No Diamond City Radio, Classical Radio and BoS distress signal. Radios are activated using main quest MQ102 now in SMU Redux. So no main quest = no radio.
