### ISSUE TITLE
VotWStarlightDriveIn.esp needs to load after PRP.esp

### ISSUE THREAD

**Issue by Regretyl** [loot/fallout4#424]
(Reposted from discord by request) 
Hello, I wanted to bring up an issue I found between 2 mods in Fallout 4 in order to potentially have a permanent rule added to LOOT if deemed appropriate.  I have a detailed write up [here](https://forums.nexusmods.com/index.php?showtopic=5666067/#entry103458738) regarding the issue.

The short version is that VotWStarlightDriveIn.esp ([Videos of the Wasteland Addon - Starlight Drive-In Module v2.2.1](https://www.nexusmods.com/fallout4/mods/24435)) needs to be loaded after PRP.esp ([Previsibines Repair Pack](https://www.nexusmods.com/fallout4/mods/46403)) in order for a quest to repair the drive-in movie screen to work effectively and also to prevent a CTD that can occur within the same cell if clicking on a stack of film reels which VOTW changes to be actual film reels.

I had a chance to speak with the author of PRP earlier today and they suggested I raise the issue here as there may not be a way to patch it, and the author of VOTW has been inactive for quite some time now.

**Comment by sibir-ine** [comment]
@Regretyl Done, thanks for the report!
