### ISSUE TITLE
Not a programmer, but reporting UDR on Rad-Ban Eyewear Armorsmith patch 1.01

### ISSUE THREAD

**Issue by Pinute** [loot/fallout4#47]
I'm sure that I'm not putting this together correctly or even if I'm supposed to report this here but here goes. 

The Armorsmith Eyewear Mod patch version 1.01 dated 11:10, 19 April 2016 for Rad-Ban Eyewear Inc. 
 http://www.nexusmods.com/fallout4/mods/8342/? has one undeleted reference at 002456ED . 

Confirmed using xEdit 3.2's Undelete and Disable References script. I'm not sure how you're calculating crc's so I'm not providing one.

I'm not sure that this matters, but there have been reports of crashing while using that plugin. I had that issue and cleaning the esp allowed the game to load.

**Comment by Freso** [comment]
Hi. :) I'll look into it! (This happens to one of the mods in my current load order too… Guess it slipped past my checking this one.)

If you load the plugins in LOOT and sort the load order, LOOT will show you the CRC. Obviously this should be done on the uncleaned mod, as the CRC will change once you alter the plugin file in any way.

Thanks for the heads up, I'll try and get it added this weekend!
