### ISSUE TITLE
FROST - update notes

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout4#474]
### [FROST Cell Fixes (FCF)](https://www.nexusmods.com/fallout4/mods/59652/)

Replaces both [FROST - Interior Cell Fixes -DEPRECATED-](https://www.nexusmods.com/fallout4/mods/48425/) and [FROST - Exterior Cell Fixes -DEPRECATED-
](https://www.nexusmods.com/fallout4/mods/54950/)

---

[-DEPRECATED- FROST - Workshop DLC Patch -DEPRECATED-](https://www.nexusmods.com/fallout4/mods/48699/)
Included in `RedsFrostFixes.esp` [FROST Official Updates (previously FROST Unofficial Updates)](https://www.nexusmods.com/fallout4/mods/48839)
- [x] Remove patch message.

---

[-DEPRECATED- FROST Survival Kit -DEPRECATED-](https://www.nexusmods.com/fallout4/mods/53252)
Included in `RedsFrostFixes.esp` [FROST Official Updates (previously FROST Unofficial Updates)](https://www.nexusmods.com/fallout4/mods/48839)
- [x] Add already in X message.

**Comment by sibir-ine** [comment]
I believe all of the necessary changes were made in #450, but the mod has had a few changes since then (i.e., new patches, a hotfix, possibly new load rules & another mod reported as integrated) that would warrant an update.

**Comment by MacSplody** [comment]
> I believe all of the necessary changes were made in #450, but the mod has had a few changes since then (i.e., new patches, a hotfix, possibly new load rules & another mod reported as integrated) that would warrant an update.

Okay that's fine, I'll use the issue for any metadata related to deprecated files, that may need updates.

**Comment by MacSplody** [comment]
Could also be of use 
[Below Zero - A FROST Modding Guide - Load Order](https://redawt.github.io/f4-frost-guide/normallo.html)
Load order checker provided here as well.

[Below Zero - A FROST Modding Guide - Compatability](https://redawt.github.io/f4-frost-guide/compatability.html)
[Nexus Article - Incompatible Mods](https://www.nexusmods.com/fallout4/articles/3393/)
