### ISSUE TITLE
Failing to apply Mod load order.

### ISSUE THREAD

**Issue by Teacyn** [loot/fallout4#48]
Getting the attached error when attempting to click "Apply" after sorting load order for Fallout 4.

[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/1181769/LOOTDebugLog.txt)

[CEFDebugLog.txt](https://github.com/loot/fallout4/files/1181770/CEFDebugLog.txt)

[No LOOTAPIDebugLog.txt is being generated. ](http://i.imgur.com/g81gLyH.png)

**Comment by Ortham** [comment]
`
[21:41:34.262978] [error]: libloadorder failed to set the load order. Details: "C:\Users\misne\AppData\Local\Fallout4\plugins.txt" could not be written. Details: ios_base::badbit set: iostream stream error: Libloadorder error
`

Check that your `plugins.txt` is not read-only.

**Comment by Ortham** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
