### ISSUE TITLE
An error occured while parsing the masterlist

### ISSUE THREAD

**Issue by Jtreu** [loot/fallout4#49]
I have this red box error when using loot that says:

"An error occurred while parsing the masterlist: yaml-cpp: error at line 11, column 9: bad conversion: 'str' key missing from 'message content' object. This probably happened because an update to LOOT changed its metadata syntax support. Try updating your masterlist to resolve the error."

Even after deleting LOOT along with my user settings and doing a fresh install from the newest repo, I still have this error. 

Suggestions?

**Comment by Ortham** [comment]
Travis thinks the masterlist is OK, what version of LOOT are you using, and what's the masterlist branch value in your LOOT settings for Fallout 4?
