### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by AlonmifexMaximus** [loot/fallout4#5]
Caused when applying Sort Decision to LO's. 

Error code: 1; libloadorder failed to set the load order. Details: "C:\Users\alonl\AppData\Local\Fallout4\plugins.txt" could not be written. Details: ios_base::badbit set: iostream stream error

**Comment by unforbidable** [comment]
See loot/loot#518.

**Comment by Ortham** [comment]
Yes, this is a duplicate of the above linked issue (I edited the post to tidy up the link), so closing this.
