### ISSUE TITLE
Fallout 4 Metadata was never there

### ISSUE THREAD

**Issue by olivadelrio** [loot/fallout4#523]
![Screenshot (18)](https://user-images.githubusercontent.com/116208462/196779585-c5f466e8-fa3a-4407-9ff9-0542af1faceb.png)

**Comment by sibir-ine** [comment]
Please try updating your masterlist.

**Comment by sibir-ine** [comment]
Closing as there hasn't been a response in a week. Feel free to leave a comment if you're still having issues, or ask for help in our [Discord](https://loot.github.io/discord/) or [forum thread](https://loot.github.io/latest-thread/).
