### ISSUE TITLE
M8r98a4f2's Complex Item Sorter

### ISSUE THREAD

**Issue by Willlux** [loot/fallout4#538]
This should be one of the files right at the bottom of the load order, along with M8r Complex Sorter.esp, but for some reason LOOT always sorts it above a few random mods, resulting in the M8r_Complex Sorter script in xEdit spitting out an error.

![Screenshot 2023-02-25 112717](https://user-images.githubusercontent.com/19621640/221354427-113b47d8-4ab4-4707-8900-71e912118179.png)

**Comment by sibir-ine** [comment]
Is this plugin only generated by an xEdit script? If so, can you please link to the script, & is the name enforced by the script or recommended by the author? If so, we could add a rule for it. If not, there's nothing we can do if a user names it whatever they want as we can't possibly predict what every user will name it, & we don't add metadata for users' private plugins. You'd have to edit the plugin's metadata & add it to, e.g., the **Dynamic Patches** group or a custom group.

**Comment by Willlux** [comment]
Sure, the script is here: https://www.nexusmods.com/fallout4/mods/48826, and the name is indeed set by the script automatically.
Thanks for the quick response!
Edit: To note, the script can generate multiple -part esps, I have 2 parts with about 500 mods, but I suppose it could have more of them.

**Comment by sibir-ine** [comment]
You're welcome, thanks for the report!
