### ISSUE TITLE
Settings not updating or detecting Fallout 4

### ISSUE THREAD

**Issue by ghost** [loot/fallout4#54]
[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/1523911/LOOTDebugLog.txt)
Version 0.12.0

After uninstalling 11.0 of Loot, and deleting the folder in the appdata, I installed 0.12.0 and noticed that it only detected Skyrim Special edition, and not Fallout 4. So I went into settings and manually inputted the installation path for Fallout 4, however, this did not work. The Settings do not stay when the program is exited, and Fallout 4 isnt selectable.

Steps I have tried:
Making the Appdata folder for loot NOT Read-only
Running loot Via NMM
Converting 11.0 Yaml file to work with 0.12.0 's new settings file format using online converter.

EDIT: The issue seems to of resolved itself when Debug Logging was enabled. However, Disabling the logging creates the problem again.

**Comment by Ortham** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html), particularly the bit about how to supply your logs.

**Comment by ghost** [comment]
I have supplied a log, and made a small edit to the original post.

**Comment by Ortham** [comment]
I can't see why no logging would interfere with game detection, and I don't have space to install Fallout 4, but I can see there's something odd going on with loading / saving settings...

**Comment by Ortham** [comment]
OK, I spotted why debug logging was involved, it was a pretty stupid mistake, try [this build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.0-2-g147856d_fix-settings.7z).

**Comment by ghost** [comment]
The build does appear to work properly :D

**Comment by Ortham** [comment]
Great, closing this then.
