### ISSUE TITLE
error 5

### ISSUE THREAD

**Issue by LuxciferX88** [loot/fallout4#55]
cuando realizo la acción ordenar plug al final del proceso me aparece un mensaje de error

**Comment by Ortham** [comment]
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html). In particular, I need your debug logs.

**Comment by Ortham** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
