### ISSUE TITLE
Error sort load order

### ISSUE THREAD

**Issue by Kasanas** [loot/fallout4#57]
Hello, I got an error when I try to sort load order. I join the debug files.
[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/1714526/LOOTDebugLog.txt)
Can you help me please ?

**Comment by Kasanas** [comment]
I don't know why but NMM solved the problem by seting plugins.txt as not read only

**Comment by Ortham** [comment]
That'll be because the problem was that your plugins.txt was read-only. LOOT can't update a read-only load order.
