### ISSUE TITLE
Potential issue with warning for llamaCompanionHeather.esp and Armoursmith Extended

### ISSUE THREAD

**Issue by AnyOldName3** [loot/fallout4#59]
I think there's a potential issue with the condition here https://github.com/loot/fallout4/blob/v0.10/masterlist.yaml#L2325 but I don't know what it is as at first glance it seems to make sense.

As can be seen in the following screenshot, even though I have a plugin active which seems to match the regular expression, I still get the warning:

![capture](https://user-images.githubusercontent.com/8485112/36512847-4d97d972-1764-11e8-8911-213f92ef7a5b.PNG)

I included the relevant part of the masterlist in the screenshot to show that it is indeed up to date.

There's a chance that the issue comes from loading LOOT from within a slightly dodgy Mod Organizer build, but I suspect that that's unrelated as the file shows up just fine in the plugins list.

**Comment by Ortham** [comment]
That looks like it should work, if you [upload your debug log](https://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html) that might shed some light on what's happening.

**Comment by AnyOldName3** [comment]
It literally just contains the following warning about loading a font file:

```
[14:11:09.639586] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
```

I don't imagine that that's related to the issue I'm seeing.

I'm going to attempt to replicate the issue under simpler conditions (e.g. with fewer plugins activated or without Mod Organizer involved) and see if something makes it go away.

**Comment by AnyOldName3** [comment]
I've tested from outside Mod Organizer, and the issue goes away. This means that either one of the zillion other plugins I have causes the issue, whether or not it's activated, or it's an issue with MO. I'm going to assume the latter and close this.

**Comment by Ortham** [comment]
OK, if you can replicate the issue without MO, feel free to reopen the issue.
