### ISSUE TITLE
Cyclic interaction between `StartMeUp.esp` & `WorkshopRearranged.esp`

### ISSUE THREAD

**Issue by crimsonfirecat** [loot/fallout4#600]
I received this error when trying to sort:

> Cyclic interaction detected between: "StartMeUp.esp" and "Eli_Display Shelves.esp":
> StartMeUp.esp
> [Master]
> StartMeUpNukaworldPatch.esp
> [Masterlist Group]
> WorkshopRearranged.esp
> [Master]
> Eli_Display Shelves.esp
> [Masterlist Group]
> StartMeUp.esp

I tried an old solution I found while searching but it didn't seem to fix anything; I'm not very coding/modding savvy OTL

**Comment by sibir-ine** [comment]
Looks like an issue on our end. You can fix it for now by adding a load after rule between `StartMeUp.esp` & `WorkshopRearranged.esp` (don't know about the order, I'd recommend opening them in xEdit to see which one you want to load later or if it matters at all).
**Edit**: looks like they don't conflict, either order should be fine.

**Comment by sibir-ine** [comment]
`Low Priority Overrides` appears to be getting pretty big, so it might be worth splitting it up.

**Comment by crimsonfirecat** [comment]
> Looks like an issue on our end. You can fix it for now by adding a load after rule between `StartMeUp.esp` & `WorkshopRearranged.esp` (don't know about the order, I'd recommend opening them in xEdit to see which one you want to load later or if it matters at all). **Edit**: looks like they don't conflict, either order should be fine.

What all do I need to do to do that? I know I edit the meta data in loot but what exactly do I need to edit?

**Comment by crimsonfirecat** [comment]
> `Low Priority Overrides` appears to be getting pretty big, so it might be worth splitting it up.

Do what now???

**Comment by sibir-ine** [comment]
[Edit the metadata](https://loot.readthedocs.io/en/stable/app/usage/plugin_editor.html) of one of the plugins & add the other as a load after rule.

**Comment by crimsonfirecat** [comment]
> [Edit the metadata](https://loot.readthedocs.io/en/stable/app/usage/plugin_editor.html) of one of the plugins & add the other as a load after rule.

Thank you for the link that was a big help!

I was able to sort my plugins now, so fingers crossed I can actually, yknow.. Play the game lol
