### ISSUE TITLE
LOOT Fallout4 

### ISSUE THREAD

**Issue by dingdongthewitchisdead** [loot/fallout4#61]
Stopped working couple of days ago.
Got it working to this point:
[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/1754796/LOOTDebugLog.txt)

Warning from LOOT window:

An error occurred while parsing the metadata list(s): yaml-cpp: error at line 319, column 24: illegal map value.
Try updating your masterlist to resolve the error. If the error is with your user metadata, this probably happened because an update to LOOT changed its metadata syntax support. Your user metadata will have to be updated manually.
To do so, use the 'Open Debug Log Location' in LOOT's main menu to open its data folder, then open your 'userlist.yaml' file in the relevant game folder. You can then edit the metadata it contains with reference to the documentation, which is accessible through LOOT's main menu.
You can also seek support on LOOT's forum thread, which is linked to on LOOT's website.

Just like to know how/where to continue from this point.

**Comment by pStyl3** [comment]
Did you update to LOOT 0.12.4 already?

**Comment by Ortham** [comment]
I think I just commented on exactly the same issue report filed elsewhere, but it looks like either you LOOT or your masterlist is outdated, try updating them.

**Comment by dingdongthewitchisdead** [comment]
Working now.
Seems i needed to enable TLS 1.2 support.
