### ISSUE TITLE
PRP Metadata issue

### ISSUE THREAD

**Issue by CommissarHark** [loot/fallout4#617]
I hope I'm titling and doing this right, I've never made one of these before. PRP Branch .74 has done away with individual patches in favor of PJMs scripts being used to make personal patches for your own specific load order. LOOT still flags that there is a PRP Patch in the installer for Interiors Enhanced AIO and there isn't. You need to run Option 8 of the CheckPrevis script to create a FinalCellPatch. This is directly from a comment from PRP Mod Author, on the Interiors Enhanced page.

**Comment by MacSplody** [comment]
> I hope I'm titling and doing this right, I've never made one of these before. PRP Branch .74 has done away with individual patches in favor of PJMs scripts being used to make personal patches for your own specific load order. LOOT still flags that there is a PRP Patch in the installer for Interiors Enhanced AIO and there isn't. You need to run Option 8 of the CheckPrevis script to create a FinalCellPatch. This is directly from a comment from PRP Mod Author, on the Interiors Enhanced page.

The patch messages are removed now.
Nothing added for [PJM's Precombine - Previs Patching Scripts](https://www.nexusmods.com/fallout4/mods/69978/) yet.

**Comment by MacSplody** [comment]
> The patch messages are removed now. Nothing added for [PJM's Precombine - Previs Patching Scripts](https://www.nexusmods.com/fallout4/mods/69978/) yet.

So I asked the script author if there were any specific file names for files created by the script.
And no naming convention is enforced, so we can't really add any metadata for it,
Closing as this issue is resolved as much as possible.
