### ISSUE TITLE
Loot does not see FO4

### ISSUE THREAD

**Issue by Ssssuka** [loot/fallout4#64]
Hello friends. I am new to loot and github, I don't even understand what github is.
Okay, I hadn't played fo4 in about 5 months, but I did not uninstall it, or move it, or anything, and I did not touch loot or NMM, and now I open Loot, and FO4 is not even an option I can choose. 
[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/1805517/LOOTDebugLog.txt)
![loot](https://user-images.githubusercontent.com/37321323/37323321-f3b5c5bc-2650-11e8-85e3-1753d08d6cb4.jpg)

**Comment by Ortham** [comment]
Try running the Fallout 4 launcher.

**Comment by Ortham** [comment]
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.
