### ISSUE TITLE
Add LAST.esp and FIRST.esp for easy sorting.

### ISSUE THREAD

**Issue by TsunaMoo** [loot/fallout4#66]
The idea here would be to add certain names for easy sorting for user made additional patches.
For example a user creates a patch to improve compatibility of the mods he uses.
However depending on how many mods are not recognized by LOOT putting it dead first or dead last may be difficult.

My suggestion would be to add certain names that can be used to easily enforce placement for such user patches. 

Such as LAST.esp and FIRST.esp

For my understanding this is possible to do via useradded meta data but may require adding meta data to every unrecognized mod. 

(If I am wrong in this just close this issue.)

**Comment by Ortham** [comment]
I'd bet that there are already mods that have FIRST.esp and LAST.esp, and treating them as special names would break things...

It seems like plugin groups (loot/loot-api#20 if you've not been following things) should be adequate for solving this problem: plugins belong to the `default` group by default, so if you want to load after them, you add your patch to a group that loads after `default`, and if you want your patch to load before them, add it to a group that `default` loads after. Would that fulfill your needs?

As an aside, @WrinklyRobot only handles releases, assigning it does nothing.

**Comment by TsunaMoo** [comment]
Whoops, that assigning was supposed to go to you instead.
Yeah the idea of groups may work depending on how clear and easy it is to use.

It isn't as much a personal issue, I already solved it myself via metadata on my load order but it led to the thought that I am likely not the only one doing something like it and that it could be easier.

And yeah, I've not been following things too actively. However yesterday marked the day of my first return with a mod in a while. :)

That reminds me. What's the best way to chat with you directly WrinklyNinja?

**Comment by Ortham** [comment]
Well, the [latest dev build](https://bintray.com/wrinklyninja/loot/download_file?file_path=loot_0.12.5-12-g132dfbf_dev.7z) has groups implemented, so you can judge for yourself if it's clear and easy to use (and if it's not, feedback is welcome!).

As for getting in contact with me directly, PMing me on the Nexus forums (I'm not active there, but reply to messages) or on AFK Mods (where the LOOT thread lives) will work, but email is probably the most straightforward.

**Comment by TsunaMoo** [comment]
You don't have anything like steam or discord that you actively use?

**Comment by Ortham** [comment]
Nothing I'm on regularly, I generally don't leave chat clients running and instead just respond to email notifications. If you'd prefer something that can turn into a real-time conversation (which email and PMs aren't great for), Discord is probably best, and I think it can send email notifications so I could get one then fire up the client.

**Comment by TsunaMoo** [comment]
Discord would be nice. My Username is Tatsuto#6720

**Comment by Ortham** [comment]
Right, mine is WrinklyNinja#2573.
