### ISSUE TITLE
LOOT suddenly refused to function after installing Creation Club assets, Wrye Bash, several additional mods

### ISSUE THREAD

**Issue by Jinarra** [loot/fallout4#70]
Apologies for the enormous variety of mods - And the tastelessness of some of them - But the plugins.txt file is indeed not read-only(Empty tickbox) and I'm at my wit's end. I'm assuming it's one or more of the creation club assets, or having recently installed Wrye Bash - This has happened before, and I've had to literally 'nuke and pave' to get it working again - but it happens so rarely that I was hoping it wouldn't this time.
[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/2065790/LOOTDebugLog.txt) 
Please inform me if you need me to take any additional steps to help.

(Additionally, I have tried the updated loot API DLL listed in another thread; This changed nothing.)

**Comment by Ortham** [comment]
```
[03:34:18.260267] [error]: Exception while executing query: libloadorder failed to set the load order. Details: Access is denied. (os error 5): Libloadorder error
```

That generally means plugins.txt is read only, but you say it's not... What happens if you run LOOT as admin?

**Comment by Jinarra** [comment]
Same error. Just ran it as admin to double-check; Posting most recent debug log.
![confirmation](https://user-images.githubusercontent.com/39874392/40885390-0a418246-66eb-11e8-8506-c7d0bf3f8f7a.png)

[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/2065843/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
This sounds suspiciously similar to loot/loot#955, do you have anything else running that could have plugins.txt open or otherwise blocking other programs from writing to it?

**Comment by Jinarra** [comment]
Nothing I'm aware of. I'll try this Unlocker program you mentioned in that thread - Right now I'm uninstalling every last non-Creation Club plugin I have to cut down on probable causes. If that doesn't work, I'm going to run a steam Verify Integrity. If that doesn't work, then I'll try Unlocker. I'm fairly certain you'll want to know the results, yes?

**Comment by Ortham** [comment]
Yes please.

**Comment by Jinarra** [comment]
Uninstalling literally every mod worked; Loot now runs 'as expected' - And I suspect the error MAY have something to do with the sheer number of plugins I had. (226 not counting the Creation Club assets)

**Comment by Ortham** [comment]
libloadorder (the bit that's failing) has tests that run with thousands of plugins, so I don't think that's the reason. Let me know if it breaks when you reinstall your mods, but otherwise I'm closing this as resolved.
