### ISSUE TITLE
Error in Loot

### ISSUE THREAD

**Issue by vagrent** [loot/fallout4#71]
I get the following error in LOOT when I click on the sort button. I've removed and re-downloaded all the mods but still continue to get the error. I am running LOOT outside of the mod organizer.
Thank you for looking at this.

[LOOTDebugLog.txt](https://github.com/loot/fallout4/files/2115963/LOOTDebugLog.txt)

**Comment by MacSplody** [comment]
Details: 
Cyclic interaction detected between:
`"Radrose - Valdacil Patch - OutcastsAndRemnants.esp"` and `"3DNPC_FO4.esp".`

 Back cycle:

 `3DNPC_FO4.esp`,
` Radrose - Valdacil Patch - 3DNPC_FO4.esp`,

` AA FusionCityRising.esp`, 
`Radrose - Valdacil Patch - OutcastsAndRemnants.esp`

2 solutions to this:

Either add 
`Radrose - Valdacil Patch - 3DNPC_FO4.esp` & `Radrose - Valdacil Patch - OutcastsAndRemnants.esp` to the same group as `3DNPC_FO4.esp` & `AA FusionCityRising.esp`

Or

`3DNPC_FO4.esp` & `AA FusionCityRising.esp`  need to be separated into two different groups.

@vagrent Can you test this out and let me know if there is any further issue?

**Comment by Ortham** [comment]
> 2 solutions to this:

I think the only solution that makes sense is to move `Radrose - Valdacil Patch - 3DNPC_FO4.esp` and `Radrose - Valdacil Patch - OutcastsAndRemnants.esp` out of the `Dynamic Patches` group, because that group loads before the group their masters are in, so they're just plain in the wrong group. Putting them in `Troubled Ones` seems reasonable.

**Comment by vagrent** [comment]
Thanks for the info everyone. I moved the patches into the "troubled ones" group and all is well. Which, now that you pointed out it was nothing more than a load order issue, makes perfect sense. Thanks again for the help.

**Comment by Freso** [comment]
OP has had their issue fix and AFAICT no `Radrose - Valdacil Patch - *.esp`s are currently in any `group`(s), so it doesn't look like there's anything actionable left on this issue… so closing.

Feel free to reopen if I missed something. :)
