### ISSUE TITLE
Masterlist order change request

### ISSUE THREAD

**Issue by stripe1000** [loot/fallout4#75]
My apologies for posting this here.  I read the guidelines and honestly most of it sounded like a foreign language to me.

"Mechanist Lair Overhaul SEC.esp" should be sorted after "Scrap Everything - Ultimate Edition.esp" in the Fallout 4 masterlist.

I do not know how to edit the masterlist myself to test this or make the addition to the "pull requests" and such.  I just noticed that consistently it will sort these plugins backwards and cause CTD or Graphic glitches and I manually resort them after after every run of LOOT.  Thought you guys should know is all.

**Comment by Freso** [comment]
Can you provide a link to the/a modpage for `Mechanist Lair Overhaul SEC.esp`?

**Comment by stripe1000** [comment]
I knew I forgot something.  Sorry, here it is:
https://www.nexusmods.com/fallout4/mods/23294

**Comment by Freso** [comment]
Thanks. I'll look into it in a few hours. :)

**Comment by Freso** [comment]
Thanks for the report! It should be fixed now, but let us know if it doesn't work.
