### ISSUE TITLE
Unofficial Fallout 4 Patch doesn't sort immediately after CC plugins

### ISSUE THREAD

**Issue by Freso** [loot/fallout4#77]
If I place [`Unofficial Fallout 4 Patch.esp`](https://afkmods.iguanadons.net/index.php?/files/file/1744-unofficial-fallout-4-patch-beta/) after *or* before [`WhatsYourName.esl`](https://www.nexusmods.com/fallout4/mods/25321), [`AllSetsExtended.esl`](https://www.nexusmods.com/fallout4/mods/25316), [`ArmorKeywords.esm`](https://www.nexusmods.com/fallout4/mods/6091), and [`TrueStormsFO4.esm`](https://www.nexusmods.com/fallout4/mods/4472) and sort, UFO4P will be placed after the two `.esl` files and before the two `.esm` ones (whether related to file extension or not). Neither `WhatsYourName.esl` or `AllSetsExtended.esl` have a `group` defined, so should be in the Default group, but UFO4P is in the "Fixes" group, which should be loaded almost immediately after CC content (only the texture overhaul group is loaded sooner).

Another quirk is that after sorting and then cancelling (rather than applying), the UFO4P is gone completely from the load order (but will reappear if sorting again, and disappear again if cancelling). Not sure if related or a separate issue yet.

~I've also only tested with the 2.0.5 beta of the UFO4P, not with latest "stable" release of 2.0.4.~ Happens with both 2.0.4 and 2.0.5 (beta) of UFO4P.

Before sort, with UFO4P last in ESM-block:
```
  0  0     Fallout4.esm
           [DLCs, CCs]
254 FE  2e WhatsYourName.esl
254 FE  2f AllSetsExtended.esl
  7  7     ArmorKeywords.esm
  8  8     TrueStormsFO4.esm
  9  9     Unofficial Fallout 4 Patch.esp
```

Before sort, with UFO4P first in ESM-block:
```
  0  0     Fallout4.esm
           [DLCs, CCs]
  7  7     Unofficial Fallout 4 Patch.esp
254 FE  2e WhatsYourName.esl
254 FE  2f AllSetsExtended.esl
  8  8     ArmorKeywords.esm
  9  9     TrueStormsFO4.esm
```

After sort, in both cases:
```
  0  0     Fallout4.esm
           [DLCs, CCs]
254 FE  2e WhatsYourName.esl
254 FE  2f AllSetsExtended.esl
  7  7     Unofficial Fallout 4 Patch.esp
  8  8     ArmorKeywords.esm
  9  9     TrueStormsFO4.esm
```

**Comment by Freso** [comment]
Open LOOT, click Sort, click Cancel, exit LOOT: [LOOTDebugLog.txt](https://github.com/loot/fallout4/files/2374333/LOOTDebugLog.txt)

**Comment by Ortham** [comment]
From your log:

```
[10:58:21.551556] [trace]: Skipping edge from "Unofficial Fallout 4 Patch.esp" to "AllSetsExtended.esl" as it would create a multi-group cycle.
```

No group edges have been added at that point, only hardcoded plugin edges and a few others that seem unrelated. `AllSetsExtended.esl` is in the `default` group, `Unofficial Fallout 4 Patch.esp` is in `Fixes`. `default` loads after `Fixes`. It's not obvious to me where the cycle is. Unless it's because `Fallout4.esm` is in `default`, and `AllSetsExtended.esl` has it as a master?

**Comment by Freso** [comment]
`Fallout4.esm` doesn't have an entry in the masterlist at all, so I guess it would be in "default"… Should I try and make a
```yaml
  - name: 'Fallout4.esm'
    group: *dlcGroup
```
entry, or is this something that ought to be fixed "higher up" (or "lower down"?) in LOOT's logic? (Or both?)

**Comment by Ortham** [comment]
Try adding it as user metadata just for debugging.

**Comment by Freso** [comment]
Open LOOT, open metadata editor for `Fallout4.esm` and change group to "DLC", sort, cancel, close: [LOOTDebugLog.txt](https://github.com/loot/fallout4/files/2374724/LOOTDebugLog.txt) (same sorting result as before, and UFO4P still disappears after cancelling).

**Comment by Ortham** [comment]
I'll have to try this out myself.

**Comment by Ortham** [comment]
I can't replicate this. On starting LOOT, my load order is:

```
  0  0     Fallout4.esm
  1  1     DLCUltraHighResolution.esm
254 FE   0 ccbgsfo4004-pipboy(camo02).esl
  2  2     TrueStormsFO4.esm
           AllSetsExtended.esl
           ArmorKeywords.esm
           Unofficial Fallout 4 Patch.esp
           WhatsYourName.esl
```

![screenshot 37](https://user-images.githubusercontent.com/2430738/45594026-42f8e280-b98b-11e8-9245-63c6431474c2.png)

With the latest FO4 masterlist and no user metadata, I sort and get:

```
  0  0     Fallout4.esm
  1  1     DLCUltraHighResolution.esm
254 FE   0 ccbgsfo4004-pipboy(camo02).esl
           Unofficial Fallout 4 Patch.esp
  2  2     TrueStormsFO4.esm
           AllSetsExtended.esl
           ArmorKeywords.esm
           WhatsYourName.esl
```

![screenshot 36](https://user-images.githubusercontent.com/2430738/45594031-4a1ff080-b98b-11e8-8a8f-d2762a57d4bc.png)

If I then cancel sorting, I go back to the previous load order, and `Unofficial Fallout 4 Patch.esp` doesn't disappear from the UI.

**Comment by MacSplody** [comment]
Could https://github.com/loot/libloot/issues/51 be related to this?

**Comment by pStyl3** [comment]
Has anyone (@Freso ?) been able to replicate this issue ever since / with the latest versions of LOOT & the mentioned plugins?

Otherwise I'd say we close this issue, over 10 months have gone by without anyone else mentioning the issue so far. The issue could be reopened, if need be.

**Comment by pStyl3** [comment]
Using LOOT 0.14.5 and 
```
Unofficial Fallout 4 Patch - v2.0.8
What's Your Name - v1.8.4
All Settlements Extended - v2.0.1 (ESL version)
True Storms FO4 - v1.4
Armor and Weapon Keywords Community Resource (AWKCR) - v8.51
```
I cannot replicate the issue.
Note that `WhatsYourName.esl` has been renamed to `WhatsYourNameESL.esl`.

When I sort the following load order:
```
WhatsYourNameESL.esl
AllSetsExtended.esl
ArmorKeywords.esm
TrueStormsFO4.esm
Unofficial Fallout 4 Patch.esp
```

I get this result:
```
Unofficial Fallout 4 Patch.esp
WhatsYourNameESL.esl
AllSetsExtended.esl
ArmorKeywords.esm
TrueStormsFO4.esm
```
Which seems alright regarding UFO4P's placement.

Given that
- both Ortham and me couldn't replicate the issue
- a lot of time has gone by since opening the issue
- multiple versions of LOOT have been released in the meantime (not to mention new versions of the mods in question)
- no other instance of this issue has surfaced

I think it's best to close this issue. In case the problem resurfaces, this issue could be reopened.
