### ISSUE TITLE
Loverslab mod must load after "Start Me Up": RSE

### ISSUE THREAD

**Issue by RowanSkie** [loot/fallout4#81]
The mod is from here:
https://www.loverslab.com/files/file/6681-rse-realistic-salacious-encounters-09-30-18/

The load order with it is usually

(Other mods)
Start Me Up.esp
AAF_RSE.esp
(RSE patches)
(Scrap Everything mods, if applicable)

**Comment by RowanSkie** [comment]
Please take note that this is the only current way I know to use Github, so unless I learn how to pull requests I might clutter this issue board up.

**Comment by MacSplody** [comment]
@RowanSkie It's fine, issue trackers are built exactly for managing that problem.
If you're interested in contributing then have a look at the LOOT [How To Contribute](https://loot.github.io/docs/contributing/How-To-Contribute) page.

**Comment by RowanSkie** [comment]
Made a pull request just for this.
