### ISSUE TITLE
Out-of-date warning on AWKCR's CBBE patch

### ISSUE THREAD

**Issue by PoobahGorg** [loot/fallout4#85]
The LOOT functionality in Vortex is giving me an incorrect "Some mod dependencies are not filled" warning about how "Armor and Weapon Keywords Community Resource v5.0 - CBBE Patch v2 vv5.0 requires Armor and Weapon Keywords Community Resource v7.9 v*"

Actually . [AWKCR has been updated](https://www.nexusmods.com/fallout4/mods/6091/?tab=files) to version 8.3, while its CBBE patch remains unchanged at v2/v5.0. It seems there are a number of AWKCR users who have to use older versions of the mob for compatibility reasons (players without all the DLC). I can't say as I know the earliest version that the CBBE patch can work with, but I suspect that ti's actually lower than 7.9. Most users want to update to 8.3, there's no reason for Vortex/LOOT to be prodding users to downgrade to an older version of the mod.

**Comment by CptMcSplody** [comment]
> The LOOT functionality in Vortex is giving me an incorrect "Some mod dependencies are not filled" warning about how "Armor and Weapon Keywords Community Resource v5.0 - CBBE Patch v2 vv5.0 requires Armor and Weapon Keywords Community Resource v7.9 v*"

> "Some mod dependencies are not filled" 

@PoobahGorg This is nothing to do with LOOT, it's a Vortex feature.
